Newsweek homepage
chirchir12/newsweek-clone pull request #1
Opened 2020-04-27 19:06 UTC by chirchir12

## Newsweek clone project
- to demonstrate my understanding using bootstrap framework

2020-05-05 17:55 UTC, chirchir12 commented
## implemented homepage
* this is a clone of the Newsweek homepage ".
* The goal of the project was to learn to develop responsive layouts using bootstrap, flex, grid or float 
* The layout was achieved using the bootstrap grid system 
* The project is responsive and can accommodate small, medium and large screens 
* dummy images and content have been used repeatedly because the focus on this project is responsive design 
* I used semantic HTML to structure the markup

2020-05-06 06:55 UTC, trekab commented
# Changes Required!
Great job @chirchir12  :clap:, you have worked on most of the required features. There are a few changes to look at though.

## Required changes:
- [ ] On small screens, your latest news section is very different from the original. ([Your clone](https://github.com/trekab/images/blob/master/clone.png?raw=true), [Original](https://github.com/trekab/images/blob/master/original_site.png?raw=true))

## Optional changes:
- [ ] Make the footer logo the same image you used as the header logo. This will make your site look more like the original.

__Kindly work on the required changes and submit another code review request__
_Feel free to slack me for any inquiries_ :wink: 
__Treasure Kabareebe__

2020-05-07 18:08 UTC, rammazzoti2000 requested changes
### Hi @chirchir12 , you have a great project :+1:. did great work :tada: :rocket: 
Although there are some other issues, and some of them are crucial, that are preventing me to approve this project.

## Required Changes :construction: :raised_hands: 

- [x]  You should use Bootstrap Css classes everywhere for styling (for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_classes_requirement.png) from [Pathwrigth](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540308/))
 The goal of this project is to use them. You have made heavy use of css classes that could've been easily replaced using bootstrap classes, starting from the basic classes for styling like margins( m-0), paddings(p-0) to more important classes like display (d-block) or position (position:absolute), and so other many classes that can replace css styling
I tried to use inline comments in your css stylesheet to indicate what you need to replace, is just that they are too many, and for this I am asking you please take the time to revisit your stylesheet and determine what can be used with bootstrap and what cannot.
 I know it may be tedious, but that is the essence of this particular project.
#
- [x] The 'Main Story' section should be renamed to 'Top story' [see original website](https://www.newsweek.com/)
#
- [x] The 'Opinion' section on medium size should be properly aligned 
![image](https://user-images.githubusercontent.com/3244654/81324838-d23e9680-9097-11ea-94a4-a1c304e9ecc4.png)
#
- [x] Starting with medium size and bellow, your website is having horizontal overflow issues, also should have some margin space on both sides
#
- [x] Latest news on medium size should be properly aligned
![image](https://user-images.githubusercontent.com/3244654/81325399-95bf6a80-9098-11ea-9f9a-e6b71b997d24.png)
#
- [x] The Editor's Picks section, between 768px and 1024px, should be aligned on two column
#### Original:
![image](https://user-images.githubusercontent.com/3244654/81325915-59403e80-9099-11ea-836e-5c693c64fda9.png)
#### Clone: 
![image](https://user-images.githubusercontent.com/3244654/81326047-7c6aee00-9099-11ea-8617-dd377b5b9b69.png)
#
- [x] On medium size in the U.S., World, Business, Tech & Business, Culture, Sports , the images on the right are quite tiny
![image](https://user-images.githubusercontent.com/3244654/81326339-fac79000-9099-11ea-954e-b7e7eff806c6.png)
#
- [x] The logo in the footer on medium size is quite smaller than the original one, also shoul be the same as the original one
#### Original: 
![image](https://user-images.githubusercontent.com/3244654/81326778-93f6a680-909a-11ea-8cc3-a52f176ff60f.png)
#### Clone:
![image](https://user-images.githubusercontent.com/3244654/81326580-57c34600-909a-11ea-9c26-077735f43066.png)
#
- [ ] In css  the use of `!important` property should be avoid at any cost, please remove it and use another way for that property, see the comment bellow
#
- [x] Remove the borders from the articles in `In The Magazine` section
![image](https://user-images.githubusercontent.com/3244654/81327710-fd2ae980-909b-11ea-823d-e414d4361b86.png)


### <em>Kindly fix the REQUIRED issues and send another code review request.

Cheers and Happy coding! :clap: 

Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>

### Status: Changes required.

2020-05-07 18:08 UTC, rammazzoti2000 commented on css/style.css
> +    align-items: flex-start !important;
important property should be avoided at any cost, please remove it and find another way for that property

2020-05-07 18:09 UTC, rammazzoti2000 requested changes
### Status: Changes Required

2020-05-07 20:25 UTC, chirchir12 commented
## changes updated accordingly
# note
1. I used most of the css classes that i used could not be replaced by boostrap because they don't give me the exact styling i wanted. 
2. I used bootstrap grid for my layout and there is no place i used css for layout
3. the horizontal scroll bar appears when you have a # in front of the link like this http://127.0.0.1:5500/index.html/# can you help me figure this out. the horizontal scroll is not there when i remove the #
## THANK YOU FOR THE REVIEWS. have a look at it once again

2020-05-09 06:22 UTC, sumancrest0001 commented
**Status: Changes required** 
Awesome work @chirchir12  :clap:  :clap: :+1: 
Your project looks similar to the original one but there are minor issues that need to be addressed before moving to the next project. Please make the following changes.
**[NOTE] All the changes are mandatory.**

2020-05-09 06:25 UTC, sumancrest0001 commented on css/style.css
> +}
Let's avoid repetition of code and follow the DRY principle. [PathRight requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png). Have a look at this [article](https://speckyboy.com/good-bad-css-practices/) for reference.

2020-05-09 06:27 UTC, sumancrest0001 commented on css/style.css
> +  right: 0;
Let's remove all the repeated codes.

2020-05-09 06:30 UTC, sumancrest0001 commented
We have to fix the alignment of the newsletter and subscriber sections on large and small screens. On the large screen height of both sections should be equal. Currently, the newsletter has more.
In your project :point_down: 
![Screenshot from 2020-05-09 11-57-57](https://user-images.githubusercontent.com/37747619/81466116-c0233c00-91ee-11ea-8020-03eb70259095.png)

On the original project :point_down: 
![Screenshot from 2020-05-09 11-57-41](https://user-images.githubusercontent.com/37747619/81466123-d3cea280-91ee-11ea-93e8-1f1afc098088.png)

2020-05-09 06:34 UTC, sumancrest0001 commented
On the small screen, The newsletter section should be a single column but currently, it is divided into two. 
Have a look :point_down: 
![Screenshot from 2020-05-09 12-01-58](https://user-images.githubusercontent.com/37747619/81466171-24de9680-91ef-11ea-973e-c1ebfa1f5ae1.png)

It should be like this :point_down: 
![Screenshot from 2020-05-09 12-02-16](https://user-images.githubusercontent.com/37747619/81466195-53f50800-91ef-11ea-85ac-75e75f354a0e.png)

2020-05-09 06:36 UTC, sumancrest0001 requested changes
**Kindly make the above-requested changes and submit the project for another review.

Need help or have questions, feel free to message me on Slack (Suman Shrestha)

Happy coding !!!**

2020-05-09 10:42 UTC, chirchir12 commented on css/style.css
> +}
Hello I managed to figure this out. thanks. however how can i apply same style for different state like :hover ? kindly help

2020-05-09 11:17 UTC, chirchir12 commented
# I updated all the required changes. kindly review it again

2020-05-09 18:23 UTC, lucasmazo32 approved these changes
# Project approved :rocket:

#### Great job on implementing the required changes for the project.

#### Your project looks great!

### You can go ahead and merge this pull request!

### Happy coding! :computer:

## Lucas Mazo

2020-05-10 05:56 UTC, merged